import { ref } from 'vue'
import { useAuthStore } from '@/stores/auth'

export interface AgentMessage {
  role: 'user' | 'assistant' | 'system'
  content: string
  toolUse?: ToolUseBlock[]
  timestamp: number
}

export interface ToolUseBlock {
  id: string
  name: string
  input: string
  result?: string
}

export interface PermissionRequest {
  toolName: string
  input: Record<string, unknown>
  requestId: string
  description: string
  risk?: RiskInfo
  target?: string
}

export interface RiskInfo {
  level: 'low' | 'medium' | 'high' | 'critical'
  reason: string
}

export type AgentStatus = 'idle' | 'thinking' | 'tool_use' | 'waiting_approval' | 'disconnected' | 'error'

export function useAgentSocket(agentId: string) {
  const auth = useAuthStore()
  const connected = ref(false)
  const status = ref<AgentStatus>('idle')
  const messages = ref<AgentMessage[]>([])
  const currentText = ref('')
  const currentToolUse = ref<ToolUseBlock[]>([])
  const tokenUsage = ref<{ input: number; output: number }>({ input: 0, output: 0 })
  const costUsd = ref(0)
  const pendingApproval = ref<PermissionRequest | null>(null)

  let ws: WebSocket | null = null
  let didOpen = false

  function connect() {
    const protocol = location.protocol === 'https:' ? 'wss:' : 'ws:'
    const url = `${protocol}//${location.host}/ws/agent/${agentId}?token=${auth.token}`
    didOpen = false
    ws = new WebSocket(url)

    ws.onopen = () => {
      connected.value = true
      didOpen = true
    }

    ws.onclose = () => {
      connected.value = false
      status.value = 'disconnected'
      if (!didOpen) {
        auth.check().then((valid) => {
          if (!valid) window.location.hash = '#/login'
        })
      }
    }

    ws.onmessage = (event) => {
      try {
        const data = JSON.parse(event.data)
        handleEvent(data)
      } catch {}
    }
  }

  function handleEvent(data: Record<string, unknown>) {
    const type = data.type as string

    if (type === 'system') {
      const subtype = data.subtype as string | undefined
      if (subtype === 'init') {
        messages.value.push({
          role: 'system',
          content: `Claude Code 已连接 (${(data as Record<string, unknown>).model || 'unknown'})`,
          timestamp: Date.now()
        })
      }
    } else if (type === 'assistant_delta') {
      status.value = 'thinking'
      const deltaText = (data as Record<string, unknown>).text as string
      if (deltaText) {
        const last = messages.value[messages.value.length - 1]
        if (last && last.role === 'assistant' && !last.toolUse) {
          last.content += deltaText
        } else {
          messages.value.push({
            role: 'assistant',
            content: deltaText,
            timestamp: Date.now()
          })
        }
      }
    } else if (type === 'assistant') {
      status.value = 'thinking'
      const msg = (data as Record<string, unknown>).message as Record<string, unknown> | undefined
      const contentBlocks = msg?.content as Array<Record<string, unknown>> | undefined
      if (contentBlocks) {
        let text = ''
        const tools: ToolUseBlock[] = []

        for (const block of contentBlocks) {
          if (block.type === 'text') {
            text += block.text as string
          } else if (block.type === 'tool_use') {
            status.value = 'tool_use'
            tools.push({
              id: block.id as string,
              name: block.name as string,
              input: typeof block.input === 'string' ? block.input : JSON.stringify(block.input, null, 2)
            })
          }
        }

        if (tools.length > 0) {
          // Tool use: always a new message
          messages.value.push({
            role: 'assistant',
            content: text,
            toolUse: tools,
            timestamp: Date.now()
          })
        } else if (text) {
          // Complete text: replace the last delta-accumulated message or create new
          const last = messages.value[messages.value.length - 1]
          if (last && last.role === 'assistant' && !last.toolUse) {
            last.content = text
          } else {
            messages.value.push({
              role: 'assistant',
              content: text,
              timestamp: Date.now()
            })
          }
        }
        currentText.value = ''
        currentToolUse.value = []
      }
    } else if (type === 'user') {
      // Tool result (auto-generated by claude)
      const msg = (data as Record<string, unknown>).message as Record<string, unknown> | undefined
      const contentBlocks = msg?.content as Array<Record<string, unknown>> | undefined
      if (contentBlocks) {
        for (const block of contentBlocks) {
          if (block.type === 'tool_result') {
            const toolId = block.tool_use_id as string
            const lastMsg = [...messages.value].reverse().find((m) => m.toolUse?.some((t) => t.id === toolId))
            if (lastMsg) {
              const tool = lastMsg.toolUse?.find((t) => t.id === toolId)
              if (tool) {
                const content = block.content as string | Array<Record<string, unknown>>
                tool.result = typeof content === 'string' ? content : JSON.stringify(content)
              }
            }
          }
        }
      }
    } else if (type === 'permission_request') {
      status.value = 'waiting_approval'
      const toolInfo = data.tool as Record<string, unknown> | undefined
      const riskData = data.risk as Record<string, unknown> | undefined
      pendingApproval.value = {
        toolName: (toolInfo?.name as string) || (data.tool as string) || 'unknown',
        input: (toolInfo?.input as Record<string, unknown>) || (data.input as Record<string, unknown>) || {},
        requestId: (data.id as string) || (data.request_id as string) || '',
        description: (data.description as string) || '',
        risk: riskData ? { level: riskData.level as RiskInfo['level'], reason: riskData.reason as string } : undefined,
        target: (data.target as string) || undefined
      }
    } else if (type === 'result') {
      status.value = 'idle'
      pendingApproval.value = null
      const usage = (data as Record<string, unknown>).usage as Record<string, number> | undefined
      if (usage) {
        tokenUsage.value = {
          input: usage.input_tokens || 0,
          output: usage.output_tokens || 0
        }
      }
      const cost = (data as Record<string, unknown>).total_cost_usd as number | undefined
      if (cost) {
        costUsd.value += cost
      }
    } else if (type === 'user_message') {
      messages.value.push({
        role: 'user',
        content: (data as Record<string, unknown>).content as string,
        timestamp: Date.now()
      })
    } else if (type === 'replay_done') {
      status.value = 'idle'
    } else if (type === 'error') {
      status.value = 'error'
      messages.value.push({
        role: 'system',
        content: `错误: ${(data as Record<string, unknown>).error || 'unknown'}`,
        timestamp: Date.now()
      })
    } else if (type === 'exited') {
      status.value = 'disconnected'
      messages.value.push({
        role: 'system',
        content: '代理进程已退出',
        timestamp: Date.now()
      })
    }
  }

  function sendMessage(content: string) {
    if (!ws || ws.readyState !== WebSocket.OPEN) return
    ws.send(JSON.stringify({ type: 'message', content }))
    messages.value.push({
      role: 'user',
      content,
      timestamp: Date.now()
    })
    status.value = 'thinking'
  }

  function respondPermission(granted: boolean) {
    if (!ws || ws.readyState !== WebSocket.OPEN || !pendingApproval.value) return
    ws.send(
      JSON.stringify({
        type: 'permission_response',
        payload: {
          type: 'permission_response',
          id: pendingApproval.value.requestId,
          approved: granted
        }
      })
    )
    pendingApproval.value = null
    status.value = granted ? 'tool_use' : 'thinking'
  }

  function close() {
    ws?.close()
    ws = null
    connected.value = false
  }

  return {
    connected,
    status,
    messages,
    currentText,
    currentToolUse,
    tokenUsage,
    costUsd,
    pendingApproval,
    connect,
    sendMessage,
    respondPermission,
    close
  }
}
